version: '2'

services:

    abp_host:
        image: bishoymly/host
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
        ports:
            - "9901:80"
        depends_on:
            - db

    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"

    abp_ng:
        image: bishoymly/ng
        ports:
            - "9902:80"

    abp_simulator:
        image: bishoymly/simulator